### ISSUE TITLE
Other properties for Document

### ISSUE THREAD

**Issue by alelordelo** [btfranklin/CleverBird#10]
Would be great to be able to define other properties for embedding Document, ex name, description.

**Comment by btfranklin** [comment]
Let me just make sure I understand what you're asking for. You mean essentially some metadata that is not part of the embedded document text itself, yes? I'd prefer to keep the implementation as minimal inside CleverBird itself as possible, but I think with some small improvements, I could make it easy to support things like this. I will look into it.

In the meantime, to add the type of metadata you're after, I believe all you really need to do is create your own data struct that has the metadata you're wanting (such as name and description) and put it into a Dictionary where the Document is the key, and the metadata struct is the value. Then, for example, whenever you get back a Document from a similarity query, you just have to use that same Document to get the associated metadata struct from your Dictionary, and you're done.

**Comment by btfranklin** [comment]
After thinking this over a bit more, this is out of scope for the design here, because "document" is really meant to be a very simple string value, not necessarily a "document" in the traditional sense. For example, as "document" might just be a sentence of text.
