### ISSUE TITLE
Functions

### ISSUE THREAD

**Issue by pascalfribi** [btfranklin/CleverBird#11]
I am unable to use functions.

First of all the method ChatThreas.addFunctionResponse is not marked public, so I cannot add an response from a function call.
Second if I set it to public and call the completion, chat GPT sends statusCode 400 telling that an object is not of type string.

No idea what is going wrong here.

**Comment by pascalfribi** [comment]
Please approve Pull Request #12 . I have fixed the functions and it is now working properly.

**Comment by btfranklin** [comment]
Thank you very much for the PR addressing this! It looks like the build fails, but I've reviewed your changes and I will make whatever adjustments needed to get the build passing again.
