### ISSUE TITLE
Response status code was unacceptable: 404

### ISSUE THREAD

**Issue by colbyn** [btfranklin/CleverBird#6]
The following
```swift
let openAIAPIConnection = OpenAIAPIConnection(apiKey: CHATGPT_API_KEY)
let chatThread = ChatThread(connection: openAIAPIConnection)
    .addSystemMessage("You are a helpful assistant.")
    .addUserMessage("Who won the world series in 2020?")
let completion = try! await chatThread.complete()
print(completion)
```

Fails at runtime with the following message:
```
Fatal error: 'try!' expression unexpectedly raised an error: CleverBird.CleverBirdError.requestFailed(message: "Response status code was unacceptable: 404.")
```

I have yet to determine if it's me or the library.

**Comment by colbyn** [comment]
Using the `.gpt35Turbo` model I get
```
CleverBird.CleverBirdError.requestFailed(message: "Response status code was unacceptable: 429.")
```

**Comment by btfranklin** [comment]
The 429 response code is described thusly: The HTTP 429 Too Many Requests response status code indicates the user has sent too many requests in a given amount of time ("rate limiting")

That makes me think it's something on your side. Please let me know if you're unable to resolve this problem after waiting a bit. You might want to log into your OpenAI account and look at the "usage" tab to see what's going on.

**Comment by colbyn** [comment]
@btfranklin Yeah you may be right. I'll post any updates I encounter.

**Comment by btfranklin** [comment]
@colbyn Did you resolve this? If not, do you have any additional information?

**Comment by btfranklin** [comment]
@colbyn FWIW, I am now seeing 429 errors during my own local tests, which make no sense. I'm honestly not sure what might be going on. Let me know if you have any update.

**Comment by btfranklin** [comment]
Closed this issue since I assume it has been resolved. Please feel free to re-open if the problem happens again.
