### ISSUE TITLE
Function calling on stream mode

### ISSUE THREAD

**Issue by alelordelo** [btfranklin/CleverBird#7]
Thanks for this great library!

Is it possible to call a function on stream mode (and not get it response streamed)?

Ex: 
Messages are streamed
Func calls are not streamed

**Comment by btfranklin** [comment]
At present, function calling is not supported in streamed mode. (This is mentioned in the README.) I'd like to add support for this ability in the future, though.

**Comment by alelordelo** [comment]
Yes, I know it’s not supported. But what I had in mind is something like  having stream for messages and not stream for functions on the same chat. Do you think this is doable?On 17 Sep 2023, at 04:00, B.T. Franklin ***@***.***> wrote:﻿
At present, function calling is not supported in streamed mode. (This is mentioned in the README.) I'd like to add support for this ability in the future, though.

**Comment by btfranklin** [comment]
Hey there. I have now had a chance to properly investigate this, and it appears to me from my API tests that there is no support on OpenAI's side for function calling in streaming mode. It simply ignores the defined functions as if they didn't exist, and reverts to "I'm just an AI and can't do that" messages.

So what this means, unfortunately, is that there's just no way to do it at the moment with the current API.

I'm going to close this out, but if this capability is introduced in the future by OpenAI, I'd be very happy to add support.

**Comment by alelordelo** [comment]
@btfranklin , I almost got it working using this package. I can stream the chat and print the function arguments, but still struggling to get the function arguments passed to the view... Your package is much cleaner, so I am trying to get this working on CleverBird : )
https://github.com/MacPaw/OpenAI/issues/96#issuecomment-1731554676

**Comment by btfranklin** [comment]
That sounds really cool. If you would like open a PR against CleverBird with your implementation once you get it working, I would be happy to consider it for integration into the package. I'll go ahead and re-open this ticket since you're actively looking into this. Please do follow up with how it goes!

**Comment by alelordelo** [comment]
looks like openAI is also struggling to get function calling streamed:

[Limitations](https://platform.openai.com/docs/assistants/how-it-works/limitations)
Support for streaming output (including Messages and Run Steps).

**Comment by alelordelo** [comment]
from the latest GPT4 Turbo

**Comment by btfranklin** [comment]
I'm going to go ahead and close this, since a long time has passed and I haven't heard more.
